# Generated by Django 5.1.1 on 2024-10-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Action title')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_action', to='main.action', verbose_name='ActionLog Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_user', to='main.user', verbose_name='ActionLog User')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_userprofile', to='main.userprofile', verbose_name='ActionLog User-Profile')),
            ],
        ),
    ]
