# Generated by Django 5.1.1 on 2024-10-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_action_actionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.action'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
