# Generated by Django 5.1.1 on 2024-10-02 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_profile_picture_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
